### ISSUE TITLE
idea打包似乎无法使用？

### ISSUE THREAD

**Issue by Joackk** [Suq3rm4n/java-impacket-gui#1]
在这里和以前用的选项似乎很少，也提示编译成功，jar文件也有就是运行不了，请问这是哪里的问题哇
![image](https://github.com/Suq3rm4n/java-impacket-gui/assets/45162558/a1ef9ef6-2d69-4fd9-98ed-24d59be69c7c)

**Comment by Suq3rm4n** [comment]
已上传jar包

**Comment by Joackk** [comment]
> 已上传jar包

这个jar包我也打包到了，但是运行没反应哇，是有什么条件吗？

**Comment by Suq3rm4n** [comment]
生成的包名和运行错误结果看一下

**Comment by Joackk** [comment]
> 生成的包名和运行错误结果看一下

运行没错误，就是没反应，试了下大佬你发的也是运行啥反应都没有，是要丢到impact里吗？

**Comment by Joackk** [comment]
> 生成的包名和运行错误结果看一下

这里打包也没提示错误
![image](https://github.com/Suq3rm4n/java-impacket-gui/assets/45162558/00760b2d-6f6e-444f-9220-6f4ff56d9855)

**Comment by Suq3rm4n** [comment]
![image](https://github.com/Suq3rm4n/java-impacket-gui/assets/56992826/01089c65-c03c-4ce0-a5e2-2b7fbc13868c)嗯，jar包跟impacket放平级目录就行了

**Comment by Joackk** [comment]
> ![image](https://user-images.githubusercontent.com/56992826/265570451-01089c65-c03c-4ce0-a5e2-2b7fbc13868c.png)嗯，jar包跟impacket放平级目录就行了

确认了似乎是我java版本的问题，我朋友他们用8是正常的，我似乎是11
