### ISSUE TITLE
UI缩放不正常

### ISSUE THREAD

**Issue by LztCode** [Suq3rm4n/java-impacket-gui#3]
如题：UI在Mac下跟老人机一样
<img width="1280" alt="image" src="https://github.com/Suq3rm4n/java-impacket-gui/assets/73683679/28b32811-9f2b-49cc-822f-15ea16da2ae4">

**Comment by Suq3rm4n** [comment]
改过了，没有Mac自行下载编译测试反馈
![image](https://github.com/Suq3rm4n/java-impacket-gui/assets/56992826/779b2a46-1ccf-4416-bbb3-dd106dc1b011)

**Comment by LztCode** [comment]
大佬，没有看到commit啊，改了哪

**Comment by Suq3rm4n** [comment]
> 大佬，没有看到commit啊，改了哪

没注意commit失败了，重传了

**Comment by LztCode** [comment]
ok了
